# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNKkoZba6WrOjGR-1AMR4RK9L-I8d6XD
"""

from .mcp import CustomerDatabaseMCP